### ISSUE TITLE
keyring.errors.NoKeyringError: No recommended backend was available.

### ISSUE THREAD

**Issue by Dunrar** [OzzieIsaacs/calibre-web-test#76]
When trying to run the test, I encountered the following error: 

```
Traceback (most recent call last):
  File "/home/<user>/OpenSource/./calibre-web-test/test/main.py", line 13, in <module>
    from helper_func import kill_dead_cps, finishing_notifier, poweroff
  File "/home/<user>/OpenSource/calibre-web-test/test/helper_func.py", line 39, in <module>
    from config_email import E_MAIL_ADDRESS, E_MAIL_SERVER_ADDRESS, STARTSSL, EMAIL_SERVER_PORT
  File "/home/<user>/OpenSource/calibre-web-test/test/config_email.py", line 8, in <module>
    E_MAIL_PASSWORD = keyring.get_password('system', E_MAIL_ADDRESS)
  File "/home/<user>/OpenSource/calibre-web/venv/lib/python3.10/site-packages/keyring/core.py", line 55, in get_password
    return get_keyring().get_password(service_name, username)
  File "/home/<user>/OpenSource/calibre-web/venv/lib/python3.10/site-packages/keyring/backends/fail.py", line 25, in get_password
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
```

The keyring package was installed, but I had to install the keyrings.alt package by hand in order to progress.

System: Manjaro 21.3.5
Python Version: 3.10

**Comment by OzzieIsaacs** [comment]
I changed the example config file to accept a plain password in the file
